### ISSUE TITLE
1.6.0 does not compile

### ISSUE THREAD

**Issue by mcf-rocks** [AcalaNetwork/Acala#1610]
The latest Karura build does not compile on ubuntu 20.04 rust 1.55.0-nightly

do this
```
git clone https://github.com/AcalaNetwork/Acala.git
cd Acala
git checkout 1.6.0
make init
make build
```

after some time you will get the failure:
```
error: internal compiler error: encountered incremental compilation error with evaluate_obligation(1eb4b304d78c5f26-6aad93738ab8ef09)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p acala_runtime` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(1eb4b304d78c5f26-6aad93738ab8ef09): Ok(EvaluatedToOk)', /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/compiler/rustc_query_system/src/query/plumbing.rs:624:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (a85f584ae 2021-06-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `(frame_system::CheckSpecVersion<Runtime>, frame_system::CheckTxVersion<Runtime>, frame_system::CheckGenesis<Runtime>, frame_system::CheckMortality<Runtime>, frame_system::CheckNonce<Runtime>, frame_system::CheckWeight<Runtime>, module_transaction_payment::ChargeTransactionPayment<Runtime>, module_evm::SetEvmOrigin<Runtime>): std::cmp::Eq`
#1 [normalize_projection_ty] normalizing `Canonical { max_universe: U0, variables: [], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: All }, value: ProjectionTy { substs: [sp_runtime::generic::Block<sp_runtime::generic::Header<u32, sp_runtime::traits::BlakeTwo256>, sp_runtime::generic::UncheckedExtrinsic<sp_runtime::MultiAddress<sp_runtime::AccountId32, u32>, Call, acala_primitives::signature::AcalaMultiSignature, (frame_system::CheckSpecVersion<Runtime>, frame_system::CheckTxVersion<Runtime>, frame_system::CheckGenesis<Runtime>, frame_system::CheckMortality<Runtime>, frame_system::CheckNonce<Runtime>, frame_system::CheckWeight<Runtime>, module_transaction_payment::ChargeTransactionPayment<Runtime>, module_evm::SetEvmOrigin<Runtime>)>>], item_def_id: DefId(197:1704 ~ sp_runtime[77eb]::traits::Block::Extrinsic) } } }`
end of query stack
error: aborting due to previous error

error: build failed
make: *** [Makefile:27: build-full] Error 101
```

**Comment by mcf-rocks** [comment]
this works:

```
curl https://sh.rustup.rs -sSf | sh
 
source ~/.cargo/env
git clone https://github.com/AcalaNetwork/Acala.git
cd Acala
git checkout 1.6.0
make init
cargo build --release --features with-karura-runtime
```
